DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
	ID INT NOT NULL AUTO_INCREMENT
	, NAME VARCHAR(200) NOT NULL
	, AUTHOR VARCHAR(200) NOT NULL
	, DESCRIPTION VARCHAR(200)
	, CREATE_DATE DATE NOT NULL
	, PRIMARY  KEY(ID)
);


-- Test values
INSERT INTO BOOK (NAME,AUTHOR,CREATE_DATE) VALUES ('Сказки','Пушкин А.С.', '1831-01-01');
INSERT INTO BOOK (NAME,AUTHOR,CREATE_DATE) VALUES ('Руслан и Людмила','Пушкин А.С.', '1820-01-01');
INSERT INTO BOOK (NAME,AUTHOR,CREATE_DATE) VALUES ('Кавказский пленник','Пушкин А.С.', '1821-01-01');
INSERT INTO BOOK (NAME,AUTHOR,CREATE_DATE) VALUES ('Гавриилиада','Пушкин А.С.', '1821-01-01');
INSERT INTO BOOK (NAME,AUTHOR,CREATE_DATE) VALUES ('Братья разбойники','Пушкин А.С.', '1822-01-01');
INSERT INTO BOOK (NAME,AUTHOR,CREATE_DATE) VALUES ('Евгений Онегин','Пушкин А.С.', '1832-01-01');



INSERT INTO BOOK (NAME,AUTHOR,CREATE_DATE) VALUES ('Intoweb','Intoweb Author', '2013-01-01');
INSERT INTO BOOK (NAME,AUTHOR,CREATE_DATE) VALUES ('Intoweb v2','Intoweb Author', '2013-01-01');
INSERT INTO BOOK (NAME,AUTHOR,CREATE_DATE) VALUES ('Dev web ','Intoweb Author', '2013-01-01');